trigger:
  branches:
    include:
      - main  # Trigger on pushes to the main branch

pool:
  name: 'VPS'  # Ensure the correct pool name if using a self-hosted agent

steps:
  # Pull the latest code on your VPS
# Run docker-compose on VPS
  - task: SSH@0
    inputs:
      sshEndpoint: 'vpsConnection'
      runOptions: 'commands'
      commands: |
        cd /home/phucnghi/thrivohr/EXE201_BE_THRIVOHR
        docker compose build
        docker compose up -d
    displayName: 'Run docker-compose'

  # Verify if the container is running
  - task: SSH@0
    inputs:
      sshEndpoint: 'vpsConnection'
      runOptions: 'commands'
      commands: |
        cd /home/phucnghi/thrivohr/EXE201_BE_THRIVOHR && docker compose ps
    displayName: 'Verify running containers'
