trigger:
- main

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  dockerHubUsername: 'phucnghi'
  dockerHubImageName: 'phucnghi/thrivohr'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Deploy
  displayName: Deploy to VPS
  jobs:
  - deployment: Deploy
    displayName: Deploy to VPS
    environment: 'production'
    pool:
      name: 'VPS'  # Replace 'Default' with your self-hosted agent pool name
    strategy:
      runOnce:
        deploy:
          steps:
          - task: SSH@0
            inputs:
              sshEndpoint: 'vpsConnection'
              runOptions: 'inline'
              inline: |
                docker pull phucnghi/thrivohr:latest
                docker stop phucnghi/thrivohr || true
                docker rm phucnghi/thrivohr || true
                docker run -d --name phucnghi/thrivohr -p 80:80 phucnghi/thrivohr:latest
                docker image prune -f