trigger:
  - main

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  dockerHubUsername: 'phucnghi'
  dockerHubImageName: 'phucnghi/thrivohr'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: 'VPS'  # Make sure this matches your self-hosted agent pool name
    steps:
    - task: UseDotNet@2
      inputs:
        version: '8.x'
        includePreviewVersions: false # Be cautious with preview versions in production

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '$(solution)'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '$(solution)'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: '**/*Tests/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: Docker@2
      displayName: Build and push Docker image
      inputs:
        containerRegistry: 'dockerHubConnection'
        repository: '$(dockerHubImageName)'
        command: 'buildAndPush'
        Dockerfile: '$(dockerfilePath)'
        tags: |
          $(tag)
          latest

- stage: Deploy
  displayName: Deploy to VPS
  jobs:
  - deployment: Deploy
    displayName: Deploy to VPS
    environment: 'production'
    pool:
      name: 'VPS'  # Make sure this matches your self-hosted agent pool name
    strategy:
      runOnce:
        deploy:
          steps:
          - task: SSH@0
            inputs:
              sshEndpoint: 'vpsConnection'
              runOptions: 'inline'
              inline: |
                # Pull the latest image
                docker pull $(dockerHubImageName):latest

                # Stop and remove the old container
                docker stop thrivohr || true
                docker rm thrivohr || true

                # Run the new container
                docker run -d --name thrivohr -p 1706:8080 $(dockerHubImageName):latest

                # Remove the old image
                OLD_IMAGE=$(docker images -q $(dockerHubImageName) | sed -n 2p)
                if [ ! -z "$OLD_IMAGE" ]; then
                  docker rmi $OLD_IMAGE || true
                fi

                # Prune unused images
                docker image prune -f