trigger:
  branches:
    include:
      - main  # Trigger on pushes to the main branch

pool:
  name : VPS
steps:
  # Pull the latest code in your VPS
  - task: SSH@0
    inputs:
      sshEndpoint: 'vpsConnection'  # Define your SSH connection to the VPS in Azure DevOps
      runOptions: 'commands'
      command: |
        cd /thrivohr/EXE201_BE_THRIVOHR  # Navigate to the project folder on your VPS
        git pull origin main       # Pull the latest code from the main branch
    displayName: 'Pull latest code from repository'

  # Run docker-compose on VPS
  - task: SSH@0
    inputs:
      sshEndpoint: 'vpsConnection'
      runOptions: 'commands'
      command: |
        cd /thrivohr/EXE201_BE_THRIVOHR  # Navigate to the project folder
        docker-compose pull       # Pull any existing images if needed
        docker-compose build      # Build the Docker image from Dockerfile
        docker-compose up -d      # Start the container in detached mode
    displayName: 'Run docker-compose'
  
  # Verify if the container is running
  - task: SSH@0
    inputs:
      sshEndpoint: 'VpsConnection'
      runOptions: 'commands'
      command: docker-compose ps
    displayName: 'Verify running containers'
